<?php

namespace Nexteer\PoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * paysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paysRepository extends EntityRepository
{
}
